javascript是单线程的， 所谓单线程， 就是在程序执行时，所走的程序路径按照连续顺序排下来， 前面的必须处理好之后后面的才会执行。

那么js自上而下执行， 如果遇到一行需要执行好长时间， 后面的代码就不能正常执行， 很容易便出现了阻塞，又该如何解决呢？

好在javascript支持异步执行， 所谓异步执行是说， 程序在执行一个无法直接返回结果的代码段时， 例如数据请求，不用一直等服务器端返回数据后在执行下面的代码， 而是直接运行接下来的代码， 不管其他进程的状态， 当有消息返回时系统会通知进程进行处理， 从而提高执行效率。

那么， 单线程的javascript是怎么实现异步执行的呢，便是事件循环机制

既然javascript支持异步执行，那么怎么实现异步编程呢？常用的解决方案有以下几种：

## 回调函数

经常会遇到这样的情况， 一个操作需要依赖另一个操作， 便会出现多层回调的情况

    例1:
    function f1(callback) {
        fetch('/search').then(ret => {
            callback(ret);
        })
    }
    function f2(params) {
        fetch('/search2', params).then(ret => {
            if(ret) {
                ...
            }
        })
    }
    f1(f2);

回调方式好在易于理解代码执行， 了解代码和代码之间的关系， 但是耦合性高，阅读性差，维护困难， 多个异步操作造成回调地狱

## Promise
ES6新增了Promise, 也是异步编程的一种解决方案

Promise是一个构造函数用来生成Promise实例

    var promise = new Promise(function(resolve, reject) {
        if(true) {
            resolve(data);
        } else {
            reject(error);
        }
    })
Promise构造函数接受一个函数作为参数， 函数的两个参数是resolve和reject。

resolve 函数的作用是将Promise对象状态从 ‘未完成’ 变成 ‘成功’

reject 函数的作用是将Promise对象状态从 ‘未完成’ 变成 ‘失败’

Promise实例生成后， 可以使用.then方法分别为resolve和reject两种状态提供回调函数


    promise.then(function(value) {
        console.log('成功');
    }, function(error) {
        console.log('失败');
    })
    也可以使用箭头函数
    pomise.then(
        (value) => {console.log('成功');},
        (error) => {console.log('失败');}
    )

注意点

    var p = new Promise((resolve, reject) => {
        resolve(1);
        console.log(2);
    })
    p.then(value => {
        console.log(value);
    });
    console.log(3); 
    // 2, 3, 1
执行顺序如下
- 主线程执行
- Promise在创建后直接执行
- then方法指定的回调函数是异步任务， 推入事件队列中， 等待执行
- 继续执行主线程中的同步任务，console.log(3)
- 主线程空闲， 从事件队列中取异步任务执行， then方法开始执行
- 执行完毕

1. **Promise在创建后直接执行**
2. **调用resolve或reject并不会终结 Promise 的参数函数的执行**
3. **resolve总是在当前脚本所有同步任务执行完成后才会执行，总是最后输出**


### Promise.prototype.then()
then方法接受两个回调函数作为参数， 第二个参数是可选的

- 第一个是由pending >> redolve时的回调处理函数
- 第二个是由pending >> reject 时的回调处理函数（可选）

### Promise.prototype.catch()
用于指定发生错误时的回调函数

    pomise.then(
        (value) => {console.log('成功');}
    ).catch(error => {
        console.log(error);
    })
### Promise.prototype.finally()
用于指定无论最后Promise对象状态是什么， 都会执行finally内的操作

    pomise.then(
        (value) => {console.log('成功');}
    ).catch(error => {
        console.log(error);
    }).finally(() => {
        ...
    })
### Promise.all()
用于将多个Promise实例包装成一个新的Promise实例, 接收一个数组作为参数

    var p = promise.all([p1, p2, p3]);

p的状态由p1、p2、p3决定，分成两种情况。

（1）只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。

（2）只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。
    
### Promise.race()
用于将多个Promise实例包装成一个新的Promise实例, 接收一个数组作为参数

    var p = promise.race([p1, p2, p3]);

只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。
### Promise.resolve()
将现有对象转为Promise对象

    const jsPromise = Promise.resolve($.ajax('/whatever.json'));

### Promise.reject() 

Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。

    const p = Promise.reject('出错了');
    // 等同于
    const p = new Promise((resolve, reject) => reject('出错了'));

    p.then(null, function (s) {
        console.log(s)
    });
    // 出错了

## Generator
Generator函数是一个普通函数， 但有一下特点：
- function 关键字与函数名之间有一个*号
- 函数体内部使用yield表达式， 定义不同的状态
- 调用Generator函数会返回一个遍历器对象

        function* helloWorldGenerator() {
            yield 'hello';
            yield 'world';
            return 'ending';
            yield '呢';
        }   

        var hw = helloWorldGenerator();
        hw.next(); // {value: "hello", done: false}
        hw.next(); // {value: "world", done: false}
        hw.next(); // {value: "ending", done: true} // return语句之后便不会执行后面的代码
        hw.next(); // {value: undefined, done: true}
每次调用next方法， 就会从函数头部或者上一次停止的地方开始执行， 直到遇到yield或者return语句停止。

也就是说Generator是分段执行的， yield暂停执行， return恢复执行

next()方法可以带一个参数，该参数可以作为上一个yield表达式的返回值

for --- of循环可以直接遍历Generator函数生成的遍历器对象

    for(let i of hw){
        console.log(i);
    }
    // hello world
    但是，一旦next方法的返回对象的done属性为true，for...of循环就会中止，且不包含该返回对象，所以上面代码的return语句返回的ending，不包括在for...of循环之中

使用Generator来重写例1

    function* f() {
        const ret1 = yield fetch('/search');
        const ret2 = yield fetch('/search2', ret1);
    }
    看起来是不是明了多了， 只是在执行的时候需要使用trunk/co等内置执行


## async/await
async/await 是ES2017推出的内置执行器的Generator语法糖

有以下特点：
- 内置执行器
- 更好的语义
- 返回值是Promise

async函数返回一个 Promise 对象，可以使用then方法添加回调函数。函数执行的时候，一旦遇到await，就会先执行await后面的表达式中的内容（异步），不再执行函数体后面的语句。等到异步操作执行完毕后，再自动返回到函数体内，继续执行函数体后面的语句。

**async: 定义异步函数**
- 自动把函数转换为Promise
- 当调用异步函数时， 函数返回值会被resolve处理
- 在异步函数内可以使用await

**await: 暂停异步函数执行**
- 当使用在Promise前面时，await等待Promise完成，并返回Promise的结果
- await只能和Promise一起使用，不能和callback一起使用
- await只能用在async函数中

        async function f() {
            const rest1 = await fetch('/search');
            const rest2 = await fetch('/search2');
            return rest2
        }
        在这个例子中， 调用函数f, 首先进行网络请求search, 等到请求结果返回之后在进行第二个网络请求search2; 但是这样会浪费一定的时候， 尤其是两个请求没有任何联系的时候。当await后的内容没有相互联系的时候， 我们可以进行并发请求

        async function f() {

            const rest1 = fetch('/search');
            const rest2 = fetch('/search2');
            const rest11 = await rest1;
            const rest22 = await rest2;
            return rest22
        }
        或者
        async function f() {
            try{
                const rest1 = await Promise.all([fetch('/search'), fetch('/search2')]);
                ..
            }catch(err) {

            }
        }
        async 异步函数一般需要运行在try--catch以捕获异步任务的报错

    

改造例1:
    
    async function f() {
        const rest1 = await fetch('/search');
        const rest2 = await fetch('/search2', rest1);
        return rest2
    }
    f().then(ret => {...})





